name: build

on:
  push:
    branches:
    tags:
  pull_request:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: set up go 1.20
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
        id: go

      - name: checkout
        uses: actions/checkout@v3

      - name: build and test
        run: |
          go test -v -covermode=count ./...

